export const actionTypes = {
  LIST_FLIGHTS_SUCCESS: "LIST_FLIGHTS_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  PW_CHANGE_SUCCESS: "LOGOUT_SUCCESS",
  PW_CHANGE_ERROR: "LOGOUT_ERROR"
};
